### PR TITLE
Add link to demo video

### LINKED ISSUE #5: Create a Demo Video
We need to create a short walk through video to include with the code pattern.

@ptitzler has also recommend creating a short `gif` for the same purpose, we could possible use the gif as the image for the link to the video in the README.

### PR DESCRIPTION
**Pull request by ajbozarth**
Link to youtube video with a short walkthrough

Closes #5

### CODE REVIEW

**Comment by ajbozarth** [comment]
I've created and uploaded my video (finally). Please take a look and bring up any glaring issues that would require rerecording it (note that it's already "published" on youtube).

**Comment by stevemart** [comment]
@ajbozarth great video! a few minor comments to keep in mind for your next video.

* There's a bit of a whitenoise/static in the audio at higher volumes. Since you're using a Mac, I assume you're also using iMovie, there's an option to reduce background noise for all audio clips. Try that out, or buy a standalone mic and not the built-in one :)
* Since you made the video after the pattern was published, it would have been nice to show the code pattern page! :)
* When showing a terminal, consider increasing the font size temporarily.

**Comment by ajbozarth** [comment]
Thanks for the feedback @stevemart I actually didn't do any editing on that video, it was supposed to be a dry run but it came out like that in my first take so I decided to keep it rather than record with a better mic like I had planned. And I completely forgot to up the terminal text size >.< As for the pattern page, I thought publishing hadn't created it yet?

**Comment by stevemart** [comment]
You're right. I was confusing this one with your other pattern for some reason. Serves me right for working in the evening. :)

**Pull request merged**
