### PR TITLE
Expanded on Architecture Rough Draft

### PR DESCRIPTION
**Pull request by ajbozarth**

### CODE REVIEW

**Comment by ajbozarth** [comment]
Reminder that the image quality isn't that great because this is just a rough draft for design to base there's on.

**Comment by ajbozarth** [comment]
@djalova @MLnick is this accurate as a simple model architecture?

@stevemart @rhagarty Is this better? based on this diagram should I add python to this pattern's tags even though this repo has no python? (only the model)

**Comment by ajbozarth** [comment]
@stevemart The whole thing is in a docker container, should I replace the brain logo with a docker logo?

**Comment by stevemart** [comment]
@ajbozarth eh, up to you. The docker logo is more widely recognized but i understand you're trying to build up CODAIT mindspace. I'll leave it up to you. One thing, it's not made clear that it's in a container at all, the logo and the words used don't help with that.

**Comment by ajbozarth** [comment]
I'll update it

**Comment by ajbozarth** [comment]
merging this with the docker update based on @stevemart original approval

**Pull request merged**
