### PR TITLE
Add a prompt about the slider.

### PR DESCRIPTION
**Pull request by xuhdev**

### CODE REVIEW

**Comment by ajbozarth** [comment]
We already have this message in the form of tooltips. I can't remember which PR/Issue it was but this was decided to leave in a tooltip for cleanliness. Closing since this will not be merged.

**Comment by xuhdev** [comment]
@ajbozarth Actually I looked at the UI again and I think we should do something about it. In some cases no object is detected and the user might be very confused about what is going on in the app. In this scenario it might make sense to add a note besides the image to suggest the user to lower the threshold.

**Comment by ajbozarth** [comment]
imho I disagree, the ui itself is simplistic. Once detecting is complete there is only one remaining UI feature (if nothing is detected) and that's the slider. The slider itself has a tooltip explaining this issue. I believe cluttering up the UI for an edge case that seems clear (to me) is not necessary.

If you were to propose a UI update that somehow highlights the threshold slider feature once detection is complete if no boxes are present at the current threshold, I would be open to that, but just adding text is poor UX.

**Comment by xuhdev** [comment]
I agree that we should not clutter the UI, and the added text may not be a good idea, but my main point of issue is the confusion. Suppose the user uploads a picture and no object is detected at the threshold of 50% (which is not so unlikely). Now the only change that the user sees is the uploaded image staying on the webpage. What should the user expect? Should the user be waiting? Should the user click on somewhere? I'm happy with any solution that dissolves this confusion, not necessarily adding text.

**Comment by ajbozarth** [comment]
I understand and agree with your statement. So that raises two points from me. 

1. I believe the current UI handles that confusion in an okay way. Specifically in the case described above, the user is left with a UI with just an image, but there is only one "interactive" UX element for them to use, that is the slider. So my argument is that they would go to that. Also the slider works even when the image is being processed.

2. If you think my UX argument above is too flimsy I will describe a good UX alternative that does not rely on text but is outside my current dev time. Add a UI function that "highlights" the slider in a way to draw attention to it. This could be changing the box border to red or another color, just something subtle but distinct to say " try this slider". This function would then be called if, on detection completion, the current threshold doesn't show any boxes. It would then be cleared on any UI interaction.

So again I believe the UI is simple enough that the confusion your raising wouldn't happen, but if you're willing to put in the dev time to add a highlighting feature like I've described above I would be willing to review (and even polish) it.

**Pull request closed without merging**
