### PR TITLE
Add camera functionality to web application

### PR DESCRIPTION
**Pull request by djalova**
Adds another option to accept webcam input from user. While webcam is running, image upload is disabled until the user decides to take a picture

### CODE REVIEW

**Comment by ajbozarth** [comment]
I'll find time to give this a review today or tomorrow, but on an initial look:

`package-lock.json` should have been in the git ignore and not be committed.

**Comment by djalova** [comment]
@ajbozarth I think we should keep the `package-lock`. It contains all the dependency information.

**Comment by ajbozarth** [comment]
@djalova that's only partially correct, the package-lock "locks" the current version dependency tree in place for all those who check out the project. Meaning package.json is ignored on build and package-lock is used instead. This makes sense for a incrementally released product with version since it means updating the lock file on each release, but leaving it locked to the previous release rather than master. But for small projects like this it can instead cause odd versioning issues when developing. Given this project is essentially "complete" though it's not a big deal either way, it's just a decision I made when originally developing.

**Comment by ajbozarth** [comment]
note my suggested updates in the camera branch

**Comment by djalova** [comment]
Continuing work on the `upstream/camera` branch

**Pull request closed without merging**
